#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("FR.Droid.Resource", IsApplication=true)]

namespace FR.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ZXing.Mobile.Resource.Id.contentFrame = global::FR.Droid.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::FR.Droid.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::FR.Droid.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int MvxDropDownItemTemplate = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int MvxHttpSource = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxItemTemplate = 2130771969;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int btnClientes = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int btnDatos = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int btnDepositos = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int btnInicio = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int btnJornada = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int btnParametros = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int btnReportes = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int custom_btn_black_pearl = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int custom_btn_breaker_bay = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int custom_btn_seagull = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int fondo = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int FR = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int gradient_bg = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int gradient_bg_header = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int gradient_bg_hover = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int gradient_buttonbg = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int gradient_combobg = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int gradient_layoutbg = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ic_aceptar = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int ic_agregar = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int ic_anular = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int ic_calendario = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int ic_cancelar = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int ic_consulreten = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int ic_continuar = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int ic_devolucion = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int ic_direccion = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ic_editar = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ic_eliminar = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int ic_entrega = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int ic_guardar = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int ic_imprimir = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int ic_login = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int ic_menucli = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int ic_precio = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int ic_refresh = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int ic_regresar = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int ic_remover = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int ic_search = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int ic_visitar = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int Icon = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int Icon2 = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int list_selector = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int list_selector2 = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int login = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int mcAnular = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int mcCobros = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int mcConsignacion = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int mcConsultar = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int mcDevolucion = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int mcGarantia = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int mcInventario = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int mcPedido = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int menu_color_selector = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int passwordtxt = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int RoundButton = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int Server = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int ServerError = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int SyncClient = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int SyncError = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int SyncServer = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int text_color_selector = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int toast = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int UserTxt = 2130837567;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f04006e
			public const int Header = 2130968686;
			
			// aapt resource value: 0x7f040002
			public const int HeaderLista = 2130968578;
			
			// aapt resource value: 0x7f04006f
			public const int Items = 2130968687;
			
			// aapt resource value: 0x7f040058
			public const int ListaBonYDescs = 2130968664;
			
			// aapt resource value: 0x7f040042
			public const int ListaBonificaciones = 2130968642;
			
			// aapt resource value: 0x7f04005b
			public const int ListaCheques = 2130968667;
			
			// aapt resource value: 0x7f04008a
			public const int ListaDetalles = 2130968714;
			
			// aapt resource value: 0x7f040068
			public const int ListaDevoluciones = 2130968680;
			
			// aapt resource value: 0x7f04006b
			public const int ListaDocumentos = 2130968683;
			
			// aapt resource value: 0x7f04003b
			public const int ListaPedidos = 2130968635;
			
			// aapt resource value: 0x7f040071
			public const int ListaRetenciones = 2130968689;
			
			// aapt resource value: 0x7f04012c
			public const int ListaSugerencias = 2130968876;
			
			// aapt resource value: 0x7f040001
			public const int MvxBindableListItemTagUnique = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int MvxBindingTagUnique = 2130968576;
			
			// aapt resource value: 0x7f040048
			public const int TxtPassword = 2130968648;
			
			// aapt resource value: 0x7f040047
			public const int TxtUsuario = 2130968647;
			
			// aapt resource value: 0x7f040004
			public const int btnAceptar = 2130968580;
			
			// aapt resource value: 0x7f0400bc
			public const int btnActualizar = 2130968764;
			
			// aapt resource value: 0x7f040038
			public const int btnAgregar = 2130968632;
			
			// aapt resource value: 0x7f040060
			public const int btnAnular = 2130968672;
			
			// aapt resource value: 0x7f040089
			public const int btnBonificaciones = 2130968713;
			
			// aapt resource value: 0x7f040015
			public const int btnCambiarFecha = 2130968597;
			
			// aapt resource value: 0x7f04002f
			public const int btnCancelar = 2130968623;
			
			// aapt resource value: 0x7f0400b8
			public const int btnCarga = 2130968760;
			
			// aapt resource value: 0x7f040022
			public const int btnCheques = 2130968610;
			
			// aapt resource value: 0x7f0400a6
			public const int btnCierre = 2130968742;
			
			// aapt resource value: 0x7f0400aa
			public const int btnClientes = 2130968746;
			
			// aapt resource value: 0x7f0400b2
			public const int btnCobro = 2130968754;
			
			// aapt resource value: 0x7f0400bb
			public const int btnCobros = 2130968763;
			
			// aapt resource value: 0x7f0400b5
			public const int btnConsignacion = 2130968757;
			
			// aapt resource value: 0x7f04001a
			public const int btnConsultar = 2130968602;
			
			// aapt resource value: 0x7f040043
			public const int btnContinuar = 2130968643;
			
			// aapt resource value: 0x7f0400ad
			public const int btnDatos = 2130968749;
			
			// aapt resource value: 0x7f0400ab
			public const int btnDepositos = 2130968747;
			
			// aapt resource value: 0x7f040026
			public const int btnDescuento = 2130968614;
			
			// aapt resource value: 0x7f040152
			public const int btnDetalle = 2130968914;
			
			// aapt resource value: 0x7f0400b4
			public const int btnDevoluciones = 2130968756;
			
			// aapt resource value: 0x7f040134
			public const int btnDevolver = 2130968884;
			
			// aapt resource value: 0x7f04001c
			public const int btnEditar = 2130968604;
			
			// aapt resource value: 0x7f040024
			public const int btnEfectivo = 2130968612;
			
			// aapt resource value: 0x7f04008e
			public const int btnEliminar = 2130968718;
			
			// aapt resource value: 0x7f04001b
			public const int btnEntrega = 2130968603;
			
			// aapt resource value: 0x7f0400b9
			public const int btnEnvio = 2130968761;
			
			// aapt resource value: 0x7f04002e
			public const int btnFacturas = 2130968622;
			
			// aapt resource value: 0x7f040121
			public const int btnGPS = 2130968865;
			
			// aapt resource value: 0x7f040061
			public const int btnImprimir = 2130968673;
			
			// aapt resource value: 0x7f040057
			public const int btnInicializar = 2130968663;
			
			// aapt resource value: 0x7f04011f
			public const int btnIniciar = 2130968863;
			
			// aapt resource value: 0x7f0400a5
			public const int btnInicio = 2130968741;
			
			// aapt resource value: 0x7f0400b1
			public const int btnInventario = 2130968753;
			
			// aapt resource value: 0x7f0400af
			public const int btnJornada = 2130968751;
			
			// aapt resource value: 0x7f040049
			public const int btnLogin = 2130968649;
			
			// aapt resource value: 0x7f0400b6
			public const int btnMenuAnular = 2130968758;
			
			// aapt resource value: 0x7f0400b7
			public const int btnMenuConsultar = 2130968759;
			
			// aapt resource value: 0x7f040020
			public const int btnMonto = 2130968608;
			
			// aapt resource value: 0x7f040088
			public const int btnNota = 2130968712;
			
			// aapt resource value: 0x7f0400be
			public const int btnNotas = 2130968766;
			
			// aapt resource value: 0x7f040167
			public const int btnObservaciones = 2130968935;
			
			// aapt resource value: 0x7f0400ae
			public const int btnParametros = 2130968750;
			
			// aapt resource value: 0x7f0400b3
			public const int btnPedido = 2130968755;
			
			// aapt resource value: 0x7f040157
			public const int btnPrecio = 2130968919;
			
			// aapt resource value: 0x7f0400de
			public const int btnPrint = 2130968798;
			
			// aapt resource value: 0x7f0400ba
			public const int btnPurga = 2130968762;
			
			// aapt resource value: 0x7f040032
			public const int btnRefrescar = 2130968626;
			
			// aapt resource value: 0x7f040039
			public const int btnRemover = 2130968633;
			
			// aapt resource value: 0x7f0400ac
			public const int btnReportes = 2130968748;
			
			// aapt resource value: 0x7f040095
			public const int btnRetirar = 2130968725;
			
			// aapt resource value: 0x7f040079
			public const int btnSalir = 2130968697;
			
			// aapt resource value: 0x7f04012b
			public const int btnSeleccionarNinguno = 2130968875;
			
			// aapt resource value: 0x7f04012a
			public const int btnSeleccionarTodos = 2130968874;
			
			// aapt resource value: 0x7f040014
			public const int btnTerminar = 2130968596;
			
			// aapt resource value: 0x7f04002d
			public const int btnTipoCAmbio = 2130968621;
			
			// aapt resource value: 0x7f0400f4
			public const int btnTomaFisica = 2130968820;
			
			// aapt resource value: 0x7f0400f3
			public const int btnTrasiego = 2130968819;
			
			// aapt resource value: 0x7f040037
			public const int btnVerchq = 2130968631;
			
			// aapt resource value: 0x7f040120
			public const int btnVisitar = 2130968864;
			
			// aapt resource value: 0x7f040135
			public const int btndirA = 2130968885;
			
			// aapt resource value: 0x7f04016a
			public const int buttonZxingFlash = 2130968938;
			
			// aapt resource value: 0x7f040033
			public const int cmbBancosapc = 2130968627;
			
			// aapt resource value: 0x7f040044
			public const int cmbBancoschq = 2130968644;
			
			// aapt resource value: 0x7f0400f5
			public const int cmbBodegarli = 2130968821;
			
			// aapt resource value: 0x7f04015a
			public const int cmbClasett = 2130968922;
			
			// aapt resource value: 0x7f04003e
			public const int cmbCompanias = 2130968638;
			
			// aapt resource value: 0x7f040018
			public const int cmbCompaniasafc = 2130968600;
			
			// aapt resource value: 0x7f04003a
			public const int cmbCompaniasal = 2130968634;
			
			// aapt resource value: 0x7f04001d
			public const int cmbCompaniasap = 2130968605;
			
			// aapt resource value: 0x7f04005d
			public const int cmbCompaniasccl = 2130968669;
			
			// aapt resource value: 0x7f04006a
			public const int cmbCompaniascdcc = 2130968682;
			
			// aapt resource value: 0x7f040052
			public const int cmbCompaniascfc = 2130968658;
			
			// aapt resource value: 0x7f04004a
			public const int cmbCompaniascfp = 2130968650;
			
			// aapt resource value: 0x7f040092
			public const int cmbCompaniasci = 2130968722;
			
			// aapt resource value: 0x7f040062
			public const int cmbCompaniascncf = 2130968674;
			
			// aapt resource value: 0x7f040075
			public const int cmbCompaniascr = 2130968693;
			
			// aapt resource value: 0x7f04008b
			public const int cmbCompaniasdd = 2130968715;
			
			// aapt resource value: 0x7f04008f
			public const int cmbCompaniasdp = 2130968719;
			
			// aapt resource value: 0x7f04007a
			public const int cmbCompaniasdsc = 2130968698;
			
			// aapt resource value: 0x7f040096
			public const int cmbCompaniasdvc = 2130968726;
			
			// aapt resource value: 0x7f0400a7
			public const int cmbCompaniaslfl = 2130968743;
			
			// aapt resource value: 0x7f0400bd
			public const int cmbCompaniasmcc = 2130968765;
			
			// aapt resource value: 0x7f0400bf
			public const int cmbCompaniasmp = 2130968767;
			
			// aapt resource value: 0x7f0400c7
			public const int cmbCompaniasps = 2130968775;
			
			// aapt resource value: 0x7f0400ed
			public const int cmbCompaniasri = 2130968813;
			
			// aapt resource value: 0x7f0400f6
			public const int cmbCompaniasrli = 2130968822;
			
			// aapt resource value: 0x7f040126
			public const int cmbCompaniassr = 2130968870;
			
			// aapt resource value: 0x7f04015d
			public const int cmbCompaniastc = 2130968925;
			
			// aapt resource value: 0x7f040132
			public const int cmbCompaniastd = 2130968882;
			
			// aapt resource value: 0x7f04013e
			public const int cmbCompaniastdd = 2130968894;
			
			// aapt resource value: 0x7f04014d
			public const int cmbCompaniasti = 2130968909;
			
			// aapt resource value: 0x7f040147
			public const int cmbCompaniastp = 2130968903;
			
			// aapt resource value: 0x7f04004d
			public const int cmbCondicioncfp = 2130968653;
			
			// aapt resource value: 0x7f040054
			public const int cmbCondicionescfc = 2130968660;
			
			// aapt resource value: 0x7f040040
			public const int cmbCriterios = 2130968640;
			
			// aapt resource value: 0x7f04003c
			public const int cmbCriteriosal = 2130968636;
			
			// aapt resource value: 0x7f04005f
			public const int cmbCriterioscc = 2130968671;
			
			// aapt resource value: 0x7f040069
			public const int cmbCriterioscd = 2130968681;
			
			// aapt resource value: 0x7f040093
			public const int cmbCriteriosci = 2130968723;
			
			// aapt resource value: 0x7f040070
			public const int cmbCriterioscp = 2130968688;
			
			// aapt resource value: 0x7f04008c
			public const int cmbCriteriosdd = 2130968716;
			
			// aapt resource value: 0x7f040090
			public const int cmbCriteriosdp = 2130968720;
			
			// aapt resource value: 0x7f04007b
			public const int cmbCriteriosdsc = 2130968699;
			
			// aapt resource value: 0x7f040097
			public const int cmbCriteriosdvc = 2130968727;
			
			// aapt resource value: 0x7f0400f2
			public const int cmbCriteriosri = 2130968818;
			
			// aapt resource value: 0x7f04011b
			public const int cmbCriteriossc = 2130968859;
			
			// aapt resource value: 0x7f04015e
			public const int cmbCriteriostc = 2130968926;
			
			// aapt resource value: 0x7f04013b
			public const int cmbCriteriostd = 2130968891;
			
			// aapt resource value: 0x7f04013f
			public const int cmbCriteriostdd = 2130968895;
			
			// aapt resource value: 0x7f04014e
			public const int cmbCriteriosti = 2130968910;
			
			// aapt resource value: 0x7f040148
			public const int cmbCriteriostp = 2130968904;
			
			// aapt resource value: 0x7f04000c
			public const int cmbCuentasad = 2130968588;
			
			// aapt resource value: 0x7f04011d
			public const int cmbDiasc = 2130968861;
			
			// aapt resource value: 0x7f040019
			public const int cmbDireccionesafc = 2130968601;
			
			// aapt resource value: 0x7f04001e
			public const int cmbDireccionesap = 2130968606;
			
			// aapt resource value: 0x7f040139
			public const int cmbDiv1cd = 2130968889;
			
			// aapt resource value: 0x7f04004e
			public const int cmbDiv1cfp = 2130968654;
			
			// aapt resource value: 0x7f04013a
			public const int cmbDiv2cd = 2130968890;
			
			// aapt resource value: 0x7f04004f
			public const int cmbDiv2cfp = 2130968655;
			
			// aapt resource value: 0x7f040129
			public const int cmbEntidadessr = 2130968873;
			
			// aapt resource value: 0x7f04013d
			public const int cmbEstadoArticulotd = 2130968893;
			
			// aapt resource value: 0x7f040141
			public const int cmbEstadoArticulotdd = 2130968897;
			
			// aapt resource value: 0x7f0400a2
			public const int cmbEstadoshp = 2130968738;
			
			// aapt resource value: 0x7f04014a
			public const int cmbFamiliastp = 2130968906;
			
			// aapt resource value: 0x7f040155
			public const int cmbFamiliastpB = 2130968917;
			
			// aapt resource value: 0x7f0400c2
			public const int cmbImpresoras = 2130968770;
			
			// aapt resource value: 0x7f040142
			public const int cmbLotestf = 2130968898;
			
			// aapt resource value: 0x7f040158
			public const int cmbLotestt = 2130968920;
			
			// aapt resource value: 0x7f040076
			public const int cmbMonedascr = 2130968694;
			
			// aapt resource value: 0x7f04004c
			public const int cmbNivelPreciocfp = 2130968652;
			
			// aapt resource value: 0x7f040055
			public const int cmbNivelescfc = 2130968661;
			
			// aapt resource value: 0x7f040138
			public const int cmbPaiscd = 2130968888;
			
			// aapt resource value: 0x7f04004b
			public const int cmbPaiscfp = 2130968651;
			
			// aapt resource value: 0x7f040053
			public const int cmbPaisescfc = 2130968659;
			
			// aapt resource value: 0x7f0400c4
			public const int cmbPapeles = 2130968772;
			
			// aapt resource value: 0x7f040166
			public const int cmbRazonVisita = 2130968934;
			
			// aapt resource value: 0x7f04011c
			public const int cmbRutasc = 2130968860;
			
			// aapt resource value: 0x7f0400c8
			public const int cmbRutasps = 2130968776;
			
			// aapt resource value: 0x7f0400cb
			public const int cmbRutasrdd = 2130968779;
			
			// aapt resource value: 0x7f040156
			public const int cmbSubFamiliastp = 2130968918;
			
			// aapt resource value: 0x7f040077
			public const int cmbTipoPagoscr = 2130968695;
			
			// aapt resource value: 0x7f040165
			public const int cmbTipoVisita = 2130968933;
			
			// aapt resource value: 0x7f0400cc
			public const int cmbTiposrdd = 2130968780;
			
			// aapt resource value: 0x7f040133
			public const int cmbTipotd = 2130968883;
			
			// aapt resource value: 0x7f040159
			public const int cmbTipott = 2130968921;
			
			// aapt resource value: 0x7f04011e
			public const int cmbVisitadosc = 2130968862;
			
			// aapt resource value: 0x7f04016b
			public const int contentFrame = 2130968939;
			
			// aapt resource value: 0x7f040031
			public const int header = 2130968625;
			
			// aapt resource value: 0x7f040122
			public const int headerSF = 2130968866;
			
			// aapt resource value: 0x7f04009e
			public const int headerfctf = 2130968734;
			
			// aapt resource value: 0x7f040003
			public const int items = 2130968579;
			
			// aapt resource value: 0x7f04009f
			public const int itemsfctf = 2130968735;
			
			// aapt resource value: 0x7f040104
			public const int lbMontoCobrado = 2130968836;
			
			// aapt resource value: 0x7f040108
			public const int lbMontoFacturas = 2130968840;
			
			// aapt resource value: 0x7f040106
			public const int lbMontoPreventa = 2130968838;
			
			// aapt resource value: 0x7f0400c9
			public const int lbMontoTotal = 2130968777;
			
			// aapt resource value: 0x7f04010a
			public const int lbMontoVendido = 2130968842;
			
			// aapt resource value: 0x7f0400ee
			public const int lbTotalArticulos = 2130968814;
			
			// aapt resource value: 0x7f0400f0
			public const int lbTotalLineas = 2130968816;
			
			// aapt resource value: 0x7f040119
			public const int lblCinco = 2130968857;
			
			// aapt resource value: 0x7f040116
			public const int lblCuatro = 2130968854;
			
			// aapt resource value: 0x7f040110
			public const int lblDos = 2130968848;
			
			// aapt resource value: 0x7f040113
			public const int lblTres = 2130968851;
			
			// aapt resource value: 0x7f04010d
			public const int lblUno = 2130968845;
			
			// aapt resource value: 0x7f040008
			public const int linearLayout1 = 2130968584;
			
			// aapt resource value: 0x7f04000b
			public const int linearLayout2 = 2130968587;
			
			// aapt resource value: 0x7f04000d
			public const int linearLayout3 = 2130968589;
			
			// aapt resource value: 0x7f040034
			public const int linearLayout4 = 2130968628;
			
			// aapt resource value: 0x7f040035
			public const int linearLayout5 = 2130968629;
			
			// aapt resource value: 0x7f040036
			public const int linearLayout6 = 2130968630;
			
			// aapt resource value: 0x7f0400c3
			public const int linearLayout7 = 2130968771;
			
			// aapt resource value: 0x7f040059
			public const int linearLayout_dummy1 = 2130968665;
			
			// aapt resource value: 0x7f04003f
			public const int listaArticulos = 2130968639;
			
			// aapt resource value: 0x7f0400b0
			public const int listaOpciones = 2130968752;
			
			// aapt resource value: 0x7f04005e
			public const int listaclientes = 2130968670;
			
			// aapt resource value: 0x7f040118
			public const int lyCinco = 2130968856;
			
			// aapt resource value: 0x7f040115
			public const int lyCuatro = 2130968853;
			
			// aapt resource value: 0x7f04010f
			public const int lyDos = 2130968847;
			
			// aapt resource value: 0x7f040112
			public const int lyTres = 2130968850;
			
			// aapt resource value: 0x7f04010c
			public const int lyUno = 2130968844;
			
			// aapt resource value: 0x7f04016d
			public const int menucli = 2130968941;
			
			// aapt resource value: 0x7f040136
			public const int radioCredito = 2130968886;
			
			// aapt resource value: 0x7f04006d
			public const int radioDolar = 2130968685;
			
			// aapt resource value: 0x7f040137
			public const int radioEfectivo = 2130968887;
			
			// aapt resource value: 0x7f040098
			public const int radioGroup1 = 2130968728;
			
			// aapt resource value: 0x7f04002a
			public const int radioGroup2 = 2130968618;
			
			// aapt resource value: 0x7f04006c
			public const int radioLocal = 2130968684;
			
			// aapt resource value: 0x7f04002c
			public const int rbDolar = 2130968620;
			
			// aapt resource value: 0x7f04002b
			public const int rbLocal = 2130968619;
			
			// aapt resource value: 0x7f04012d
			public const int rdAnterior = 2130968877;
			
			// aapt resource value: 0x7f040131
			public const int rdConDoc = 2130968881;
			
			// aapt resource value: 0x7f040051
			public const int rdCredito = 2130968657;
			
			// aapt resource value: 0x7f040128
			public const int rdDolar = 2130968872;
			
			// aapt resource value: 0x7f040127
			public const int rdLocal = 2130968871;
			
			// aapt resource value: 0x7f04012f
			public const int rdNinguno = 2130968879;
			
			// aapt resource value: 0x7f04009a
			public const int rdNo = 2130968730;
			
			// aapt resource value: 0x7f0400c6
			public const int rdNoSugerir = 2130968774;
			
			// aapt resource value: 0x7f040050
			public const int rdNormal = 2130968656;
			
			// aapt resource value: 0x7f040099
			public const int rdSi = 2130968729;
			
			// aapt resource value: 0x7f040130
			public const int rdSinDoc = 2130968880;
			
			// aapt resource value: 0x7f04012e
			public const int rdSoloSaldo = 2130968878;
			
			// aapt resource value: 0x7f0400c5
			public const int rdSugerir = 2130968773;
			
			// aapt resource value: 0x7f040056
			public const int rgClase = 2130968662;
			
			// aapt resource value: 0x7f04005c
			public const int text0 = 2130968668;
			
			// aapt resource value: 0x7f040007
			public const int text1 = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int text2 = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int text22 = 2130968581;
			
			// aapt resource value: 0x7f040045
			public const int text3 = 2130968645;
			
			// aapt resource value: 0x7f040046
			public const int text4 = 2130968646;
			
			// aapt resource value: 0x7f04005a
			public const int text5 = 2130968666;
			
			// aapt resource value: 0x7f040072
			public const int text6 = 2130968690;
			
			// aapt resource value: 0x7f040123
			public const int text7 = 2130968867;
			
			// aapt resource value: 0x7f040124
			public const int text8 = 2130968868;
			
			// aapt resource value: 0x7f040125
			public const int text9 = 2130968869;
			
			// aapt resource value: 0x7f040009
			public const int textView1 = 2130968585;
			
			// aapt resource value: 0x7f040168
			public const int textView2 = 2130968936;
			
			// aapt resource value: 0x7f040169
			public const int textView3 = 2130968937;
			
			// aapt resource value: 0x7f04016c
			public const int toastText = 2130968940;
			
			// aapt resource value: 0x7f040143
			public const int txtAcumAlmacen = 2130968899;
			
			// aapt resource value: 0x7f040144
			public const int txtAcumDetalle = 2130968900;
			
			// aapt resource value: 0x7f040011
			public const int txtBanco = 2130968593;
			
			// aapt resource value: 0x7f04007c
			public const int txtBusqueda = 2130968700;
			
			// aapt resource value: 0x7f04003d
			public const int txtBusquedaas = 2130968637;
			
			// aapt resource value: 0x7f040041
			public const int txtBusquedaba = 2130968641;
			
			// aapt resource value: 0x7f04008d
			public const int txtBusquedadd = 2130968717;
			
			// aapt resource value: 0x7f040094
			public const int txtBusquedadinv = 2130968724;
			
			// aapt resource value: 0x7f040091
			public const int txtBusquedadp = 2130968721;
			
			// aapt resource value: 0x7f04013c
			public const int txtBusquedatd = 2130968892;
			
			// aapt resource value: 0x7f040140
			public const int txtBusquedatdd = 2130968896;
			
			// aapt resource value: 0x7f04014f
			public const int txtBusquedatinv = 2130968911;
			
			// aapt resource value: 0x7f040149
			public const int txtBusquedatp = 2130968905;
			
			// aapt resource value: 0x7f04014b
			public const int txtCantAlm = 2130968907;
			
			// aapt resource value: 0x7f040153
			public const int txtCantAlmGar = 2130968915;
			
			// aapt resource value: 0x7f04015b
			public const int txtCantAlmacen = 2130968923;
			
			// aapt resource value: 0x7f04014c
			public const int txtCantDet = 2130968908;
			
			// aapt resource value: 0x7f040154
			public const int txtCantDetGar = 2130968916;
			
			// aapt resource value: 0x7f04015c
			public const int txtCantDetalle = 2130968924;
			
			// aapt resource value: 0x7f0400fb
			public const int txtCantDevuelta = 2130968827;
			
			// aapt resource value: 0x7f0400fc
			public const int txtCantDevueltaDet = 2130968828;
			
			// aapt resource value: 0x7f0400f9
			public const int txtCantDisponible = 2130968825;
			
			// aapt resource value: 0x7f0400fa
			public const int txtCantDisponibleDet = 2130968826;
			
			// aapt resource value: 0x7f040102
			public const int txtCantEntradas = 2130968834;
			
			// aapt resource value: 0x7f0400a0
			public const int txtCantFacturar = 2130968736;
			
			// aapt resource value: 0x7f0400ff
			public const int txtCantGarantia = 2130968831;
			
			// aapt resource value: 0x7f040100
			public const int txtCantGarantiaDet = 2130968832;
			
			// aapt resource value: 0x7f0400f7
			public const int txtCantInicial = 2130968823;
			
			// aapt resource value: 0x7f0400f8
			public const int txtCantInicialDet = 2130968824;
			
			// aapt resource value: 0x7f0400a1
			public const int txtCantNoFacturar = 2130968737;
			
			// aapt resource value: 0x7f040103
			public const int txtCantSalidas = 2130968835;
			
			// aapt resource value: 0x7f040101
			public const int txtCantVacios = 2130968833;
			
			// aapt resource value: 0x7f0400fd
			public const int txtCantVendida = 2130968829;
			
			// aapt resource value: 0x7f0400fe
			public const int txtCantVendidaDet = 2130968830;
			
			// aapt resource value: 0x7f040023
			public const int txtCheques = 2130968611;
			
			// aapt resource value: 0x7f0400ea
			public const int txtChequesCantidad = 2130968810;
			
			// aapt resource value: 0x7f0400d9
			public const int txtChequesTotal = 2130968793;
			
			// aapt resource value: 0x7f04011a
			public const int txtCinco = 2130968858;
			
			// aapt resource value: 0x7f04000f
			public const int txtCompania = 2130968591;
			
			// aapt resource value: 0x7f0400d2
			public const int txtConTotal = 2130968786;
			
			// aapt resource value: 0x7f040063
			public const int txtConsumidFinal = 2130968675;
			
			// aapt resource value: 0x7f0400a4
			public const int txtCopias = 2130968740;
			
			// aapt resource value: 0x7f0400d3
			public const int txtCreTotal = 2130968787;
			
			// aapt resource value: 0x7f040117
			public const int txtCuatro = 2130968855;
			
			// aapt resource value: 0x7f0400dc
			public const int txtDepCantidad = 2130968796;
			
			// aapt resource value: 0x7f0400dd
			public const int txtDepTotal = 2130968797;
			
			// aapt resource value: 0x7f04000e
			public const int txtDeposito = 2130968590;
			
			// aapt resource value: 0x7f040027
			public const int txtDescuento = 2130968615;
			
			// aapt resource value: 0x7f040016
			public const int txtDescuento1 = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int txtDescuento2 = 2130968599;
			
			// aapt resource value: 0x7f0400e1
			public const int txtDevCantidad = 2130968801;
			
			// aapt resource value: 0x7f0400d4
			public const int txtDevContado = 2130968788;
			
			// aapt resource value: 0x7f0400d5
			public const int txtDevCredito = 2130968789;
			
			// aapt resource value: 0x7f0400e3
			public const int txtDevEfecCantidad = 2130968803;
			
			// aapt resource value: 0x7f0400d7
			public const int txtDevEfecContado = 2130968791;
			
			// aapt resource value: 0x7f0400d6
			public const int txtDevEfecCredito = 2130968790;
			
			// aapt resource value: 0x7f0400e4
			public const int txtDevEfecTotal = 2130968804;
			
			// aapt resource value: 0x7f0400e2
			public const int txtDevTotal = 2130968802;
			
			// aapt resource value: 0x7f040145
			public const int txtDispAlmacen = 2130968901;
			
			// aapt resource value: 0x7f040146
			public const int txtDispDetalle = 2130968902;
			
			// aapt resource value: 0x7f04009c
			public const int txtDominio = 2130968732;
			
			// aapt resource value: 0x7f040111
			public const int txtDos = 2130968849;
			
			// aapt resource value: 0x7f0400e9
			public const int txtEfecCantidad = 2130968809;
			
			// aapt resource value: 0x7f0400d8
			public const int txtEfecTotal = 2130968792;
			
			// aapt resource value: 0x7f040025
			public const int txtEfectivo = 2130968613;
			
			// aapt resource value: 0x7f040066
			public const int txtEspecial = 2130968678;
			
			// aapt resource value: 0x7f0400cd
			public const int txtFacCantidad = 2130968781;
			
			// aapt resource value: 0x7f0400cf
			public const int txtFacTFCantidad = 2130968783;
			
			// aapt resource value: 0x7f0400ce
			public const int txtFacTotal = 2130968782;
			
			// aapt resource value: 0x7f04000a
			public const int txtFecha = 2130968586;
			
			// aapt resource value: 0x7f0400e7
			public const int txtGarCantidad = 2130968807;
			
			// aapt resource value: 0x7f0400d0
			public const int txtGarContado = 2130968784;
			
			// aapt resource value: 0x7f0400d1
			public const int txtGarCredito = 2130968785;
			
			// aapt resource value: 0x7f0400e8
			public const int txtGarTotal = 2130968808;
			
			// aapt resource value: 0x7f040064
			public const int txtGubernamental = 2130968676;
			
			// aapt resource value: 0x7f04009d
			public const int txtHandHeld = 2130968733;
			
			// aapt resource value: 0x7f040085
			public const int txtLotes = 2130968709;
			
			// aapt resource value: 0x7f040012
			public const int txtMoneda = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int txtMonto = 2130968595;
			
			// aapt resource value: 0x7f040105
			public const int txtMontoCobrado = 2130968837;
			
			// aapt resource value: 0x7f040030
			public const int txtMontoEfect = 2130968624;
			
			// aapt resource value: 0x7f040109
			public const int txtMontoFacturas = 2130968841;
			
			// aapt resource value: 0x7f040107
			public const int txtMontoPreventa = 2130968839;
			
			// aapt resource value: 0x7f0400ca
			public const int txtMontoTotal = 2130968778;
			
			// aapt resource value: 0x7f04010b
			public const int txtMontoVendido = 2130968843;
			
			// aapt resource value: 0x7f0400eb
			public const int txtNcCantidad = 2130968811;
			
			// aapt resource value: 0x7f0400da
			public const int txtNcTotal = 2130968794;
			
			// aapt resource value: 0x7f040010
			public const int txtNombre = 2130968592;
			
			// aapt resource value: 0x7f040067
			public const int txtNotaCredito = 2130968679;
			
			// aapt resource value: 0x7f0400c0
			public const int txtNotas = 2130968768;
			
			// aapt resource value: 0x7f040021
			public const int txtNotasCredito = 2130968609;
			
			// aapt resource value: 0x7f040078
			public const int txtNumeroRecibo = 2130968696;
			
			// aapt resource value: 0x7f0400c1
			public const int txtOpcionMenuParametro = 2130968769;
			
			// aapt resource value: 0x7f040065
			public const int txtOrganizado = 2130968677;
			
			// aapt resource value: 0x7f0400a9
			public const int txtPass = 2130968745;
			
			// aapt resource value: 0x7f0400df
			public const int txtPedCantidad = 2130968799;
			
			// aapt resource value: 0x7f0400e0
			public const int txtPedTotal = 2130968800;
			
			// aapt resource value: 0x7f04015f
			public const int txtPrecioAlmacen = 2130968927;
			
			// aapt resource value: 0x7f040160
			public const int txtPrecioDetalle = 2130968928;
			
			// aapt resource value: 0x7f0400e5
			public const int txtRecCantidad = 2130968805;
			
			// aapt resource value: 0x7f0400e6
			public const int txtRecTotal = 2130968806;
			
			// aapt resource value: 0x7f040029
			public const int txtSaldoPendiente = 2130968617;
			
			// aapt resource value: 0x7f04001f
			public const int txtSaldoTotal = 2130968607;
			
			// aapt resource value: 0x7f04009b
			public const int txtServer = 2130968731;
			
			// aapt resource value: 0x7f040162
			public const int txtSubTotal = 2130968930;
			
			// aapt resource value: 0x7f040073
			public const int txtTipoCambio = 2130968691;
			
			// aapt resource value: 0x7f0400a3
			public const int txtTitulo = 2130968739;
			
			// aapt resource value: 0x7f0400ec
			public const int txtTotCantidad = 2130968812;
			
			// aapt resource value: 0x7f040074
			public const int txtTotal = 2130968692;
			
			// aapt resource value: 0x7f0400ef
			public const int txtTotalArticulos = 2130968815;
			
			// aapt resource value: 0x7f0400db
			public const int txtTotalCobro = 2130968795;
			
			// aapt resource value: 0x7f0400f1
			public const int txtTotalLineas = 2130968817;
			
			// aapt resource value: 0x7f040028
			public const int txtTotalPagar = 2130968616;
			
			// aapt resource value: 0x7f040114
			public const int txtTres = 2130968852;
			
			// aapt resource value: 0x7f040164
			public const int txtUbicacion = 2130968932;
			
			// aapt resource value: 0x7f040150
			public const int txtUnidadAlmacen = 2130968912;
			
			// aapt resource value: 0x7f04007d
			public const int txtUnidadAlmacenBoleta = 2130968701;
			
			// aapt resource value: 0x7f040081
			public const int txtUnidadAlmacenBueno = 2130968705;
			
			// aapt resource value: 0x7f040083
			public const int txtUnidadAlmacenMalo = 2130968707;
			
			// aapt resource value: 0x7f040086
			public const int txtUnidadAlmacenSaldo = 2130968710;
			
			// aapt resource value: 0x7f04007f
			public const int txtUnidadAlmacenVendido = 2130968703;
			
			// aapt resource value: 0x7f040151
			public const int txtUnidadDetalle = 2130968913;
			
			// aapt resource value: 0x7f04007e
			public const int txtUnidadDetalleBoleta = 2130968702;
			
			// aapt resource value: 0x7f040082
			public const int txtUnidadDetalleBueno = 2130968706;
			
			// aapt resource value: 0x7f040084
			public const int txtUnidadDetalleMalo = 2130968708;
			
			// aapt resource value: 0x7f040087
			public const int txtUnidadDetalleSaldo = 2130968711;
			
			// aapt resource value: 0x7f040080
			public const int txtUnidadDetalleVendido = 2130968704;
			
			// aapt resource value: 0x7f040161
			public const int txtUnidadExistencia = 2130968929;
			
			// aapt resource value: 0x7f040163
			public const int txtUnidadInventario = 2130968931;
			
			// aapt resource value: 0x7f04010e
			public const int txtUno = 2130968846;
			
			// aapt resource value: 0x7f0400a8
			public const int txtUser = 2130968744;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Actualizar2 = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ActualizarHeader2 = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ActualizarItem2 = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int AplicarDeposito = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int AplicarFacturaConsignacion = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int AplicarGarantia = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int AplicarPago = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int AplicarPagoContado = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int AplicarPedido = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int AplicarVentaConsignacion = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int AsignaLotes = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int AsignaLotesHeader = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int AsignaLotesItem = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int BusquedaArticulos = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int BusquedaArticulosHeaderBarras = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int BusquedaArticulosHeaderClase = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int BusquedaArticulosHeaderCodigo = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int BusquedaArticulosHeaderDescripcion = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int BusquedaArticulosHeaderFamilia = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int BusquedaArticulosItemBarras = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int BusquedaArticulosItemClase = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int BusquedaArticulosItemCodigo = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int BusquedaArticulosItemDescripcion = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int BusquedaArticulosItemFamilia = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int CambioBonificacion = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int CambioBonificacionItem = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int CambioPrecio = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int Cheques = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int ChequesHeader = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int ChequesItem = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public const int ConexionTomFisica = 2130903070;
			
			// aapt resource value: 0x7f03001f
			public const int ConfiguracionGarantia = 2130903071;
			
			// aapt resource value: 0x7f030020
			public const int ConfiguracionPedido = 2130903072;
			
			// aapt resource value: 0x7f030021
			public const int ConfiguracionVentaConsig = 2130903073;
			
			// aapt resource value: 0x7f030022
			public const int ConsultaBonYDesc = 2130903074;
			
			// aapt resource value: 0x7f030023
			public const int ConsultaBonYDescHeaderBon = 2130903075;
			
			// aapt resource value: 0x7f030024
			public const int ConsultaBonYDescHeaderDesc = 2130903076;
			
			// aapt resource value: 0x7f030025
			public const int ConsultaBonYDescItemBon = 2130903077;
			
			// aapt resource value: 0x7f030026
			public const int ConsultaBonYDescItemDesc = 2130903078;
			
			// aapt resource value: 0x7f030027
			public const int ConsultaCheques = 2130903079;
			
			// aapt resource value: 0x7f030028
			public const int ConsultaChequesHeader = 2130903080;
			
			// aapt resource value: 0x7f030029
			public const int ConsultaChequesItem = 2130903081;
			
			// aapt resource value: 0x7f03002a
			public const int ConsultaCliente = 2130903082;
			
			// aapt resource value: 0x7f03002b
			public const int ConsultaCobroHeader = 2130903083;
			
			// aapt resource value: 0x7f03002c
			public const int ConsultaCobroItem = 2130903084;
			
			// aapt resource value: 0x7f03002d
			public const int ConsultaCobros = 2130903085;
			
			// aapt resource value: 0x7f03002e
			public const int ConsultaConsecNCF = 2130903086;
			
			// aapt resource value: 0x7f03002f
			public const int ConsultaConsecNCFX = 2130903087;
			
			// aapt resource value: 0x7f030030
			public const int ConsultaConsignacion = 2130903088;
			
			// aapt resource value: 0x7f030031
			public const int ConsultaConsignacionHeader = 2130903089;
			
			// aapt resource value: 0x7f030032
			public const int ConsultaConsignacionItem = 2130903090;
			
			// aapt resource value: 0x7f030033
			public const int ConsultaCorporacion = 2130903091;
			
			// aapt resource value: 0x7f030034
			public const int ConsultaDevoluciones = 2130903092;
			
			// aapt resource value: 0x7f030035
			public const int ConsultaDevolucionesHeader = 2130903093;
			
			// aapt resource value: 0x7f030036
			public const int ConsultaDevolucionesItem = 2130903094;
			
			// aapt resource value: 0x7f030037
			public const int ConsultaDispositivo = 2130903095;
			
			// aapt resource value: 0x7f030038
			public const int ConsultaDocumentosCC = 2130903096;
			
			// aapt resource value: 0x7f030039
			public const int ConsultaDocumentosCCHeader = 2130903097;
			
			// aapt resource value: 0x7f03003a
			public const int ConsultaDocumentosCCItemDolar = 2130903098;
			
			// aapt resource value: 0x7f03003b
			public const int ConsultaDocumentosCCItemLocal = 2130903099;
			
			// aapt resource value: 0x7f03003c
			public const int ConsultaGarantias = 2130903100;
			
			// aapt resource value: 0x7f03003d
			public const int ConsultaGarantiasHeader = 2130903101;
			
			// aapt resource value: 0x7f03003e
			public const int ConsultaGarantiasItem = 2130903102;
			
			// aapt resource value: 0x7f03003f
			public const int ConsultaInventario = 2130903103;
			
			// aapt resource value: 0x7f030040
			public const int ConsultaInventarioHeader = 2130903104;
			
			// aapt resource value: 0x7f030041
			public const int ConsultaInventarioItem = 2130903105;
			
			// aapt resource value: 0x7f030042
			public const int ConsultaInvFisico = 2130903106;
			
			// aapt resource value: 0x7f030043
			public const int ConsultaInvFisicoHeader = 2130903107;
			
			// aapt resource value: 0x7f030044
			public const int ConsultaInvFisicoItem = 2130903108;
			
			// aapt resource value: 0x7f030045
			public const int ConsultaLinTomaFisica = 2130903109;
			
			// aapt resource value: 0x7f030046
			public const int ConsultaLinTomaFisicaHeader = 2130903110;
			
			// aapt resource value: 0x7f030047
			public const int ConsultaLinTomaFisicaItem = 2130903111;
			
			// aapt resource value: 0x7f030048
			public const int ConsultaNotasCredito = 2130903112;
			
			// aapt resource value: 0x7f030049
			public const int ConsultaNotasCreditoHeader = 2130903113;
			
			// aapt resource value: 0x7f03004a
			public const int ConsultaNotasCreditoItem = 2130903114;
			
			// aapt resource value: 0x7f03004b
			public const int ConsultaPedidos = 2130903115;
			
			// aapt resource value: 0x7f03004c
			public const int ConsultaPedidosHeader = 2130903116;
			
			// aapt resource value: 0x7f03004d
			public const int ConsultaPedidosItem = 2130903117;
			
			// aapt resource value: 0x7f03004e
			public const int ConsultarArticulo = 2130903118;
			
			// aapt resource value: 0x7f03004f
			public const int ConsultarArticuloDos = 2130903119;
			
			// aapt resource value: 0x7f030050
			public const int ConsultaRetenciones = 2130903120;
			
			// aapt resource value: 0x7f030051
			public const int ConsultaRetencionesHeader = 2130903121;
			
			// aapt resource value: 0x7f030052
			public const int ConsultaRetencionesItem = 2130903122;
			
			// aapt resource value: 0x7f030053
			public const int ConsultaTipoCambio = 2130903123;
			
			// aapt resource value: 0x7f030054
			public const int CreacionRecibo = 2130903124;
			
			// aapt resource value: 0x7f030055
			public const int DescuentoProntoPago = 2130903125;
			
			// aapt resource value: 0x7f030056
			public const int DescuentoProntoPagoHeader = 2130903126;
			
			// aapt resource value: 0x7f030057
			public const int DescuentoProntoPagoItem = 2130903127;
			
			// aapt resource value: 0x7f030058
			public const int DesgloceVentaConsignacion = 2130903128;
			
			// aapt resource value: 0x7f030059
			public const int DesgloceVentaConsignacionHeader = 2130903129;
			
			// aapt resource value: 0x7f03005a
			public const int DesgloceVentaConsignacionItem = 2130903130;
			
			// aapt resource value: 0x7f03005b
			public const int DetalleBonificaciones = 2130903131;
			
			// aapt resource value: 0x7f03005c
			public const int DetalleBonificacionesHeader = 2130903132;
			
			// aapt resource value: 0x7f03005d
			public const int DetalleBonificacionesItem = 2130903133;
			
			// aapt resource value: 0x7f03005e
			public const int DetalleCobro = 2130903134;
			
			// aapt resource value: 0x7f03005f
			public const int DetalleCobroHeader = 2130903135;
			
			// aapt resource value: 0x7f030060
			public const int DetalleCobroItem = 2130903136;
			
			// aapt resource value: 0x7f030061
			public const int DetalleDevoluciones = 2130903137;
			
			// aapt resource value: 0x7f030062
			public const int DetalleDevolucionesHeaderBarras = 2130903138;
			
			// aapt resource value: 0x7f030063
			public const int DetalleDevolucionesHeaderClase = 2130903139;
			
			// aapt resource value: 0x7f030064
			public const int DetalleDevolucionesHeaderCodigo = 2130903140;
			
			// aapt resource value: 0x7f030065
			public const int DetalleDevolucionesHeaderDescripcion = 2130903141;
			
			// aapt resource value: 0x7f030066
			public const int DetalleDevolucionesHeaderFamilia = 2130903142;
			
			// aapt resource value: 0x7f030067
			public const int DetalleDevolucionesItemBarras = 2130903143;
			
			// aapt resource value: 0x7f030068
			public const int DetalleDevolucionesItemClase = 2130903144;
			
			// aapt resource value: 0x7f030069
			public const int DetalleDevolucionesItemCodigo = 2130903145;
			
			// aapt resource value: 0x7f03006a
			public const int DetalleDevolucionesItemDescripcion = 2130903146;
			
			// aapt resource value: 0x7f03006b
			public const int DetalleDevolucionesItemFamilia = 2130903147;
			
			// aapt resource value: 0x7f03006c
			public const int DetalleGarantia = 2130903148;
			
			// aapt resource value: 0x7f03006d
			public const int DetalleGarantiaHeaderBarras = 2130903149;
			
			// aapt resource value: 0x7f03006e
			public const int DetalleGarantiaHeaderClase = 2130903150;
			
			// aapt resource value: 0x7f03006f
			public const int DetalleGarantiaHeaderCodigo = 2130903151;
			
			// aapt resource value: 0x7f030070
			public const int DetalleGarantiaHeaderDescripcion = 2130903152;
			
			// aapt resource value: 0x7f030071
			public const int DetalleGarantiaHeaderFamilia = 2130903153;
			
			// aapt resource value: 0x7f030072
			public const int DetalleGarantiaItemBarras = 2130903154;
			
			// aapt resource value: 0x7f030073
			public const int DetalleGarantiaItemClase = 2130903155;
			
			// aapt resource value: 0x7f030074
			public const int DetalleGarantiaItemCodigo = 2130903156;
			
			// aapt resource value: 0x7f030075
			public const int DetalleGarantiaItemDescripcion = 2130903157;
			
			// aapt resource value: 0x7f030076
			public const int DetalleGarantiaItemFamilia = 2130903158;
			
			// aapt resource value: 0x7f030077
			public const int DetalleHistoricosPedido = 2130903159;
			
			// aapt resource value: 0x7f030078
			public const int DetalleHistoricosPedidosHeader = 2130903160;
			
			// aapt resource value: 0x7f030079
			public const int DetalleHistoricosPedidosItem = 2130903161;
			
			// aapt resource value: 0x7f03007a
			public const int DetalleInventario = 2130903162;
			
			// aapt resource value: 0x7f03007b
			public const int DetalleInventarioHeaderBarras = 2130903163;
			
			// aapt resource value: 0x7f03007c
			public const int DetalleInventarioHeaderClase = 2130903164;
			
			// aapt resource value: 0x7f03007d
			public const int DetalleInventarioHeaderCodigo = 2130903165;
			
			// aapt resource value: 0x7f03007e
			public const int DetalleInventarioHeaderDescripcion = 2130903166;
			
			// aapt resource value: 0x7f03007f
			public const int DetalleInventarioHeaderFamilia = 2130903167;
			
			// aapt resource value: 0x7f030080
			public const int DetalleInventarioItemBarras = 2130903168;
			
			// aapt resource value: 0x7f030081
			public const int DetalleInventarioItemClase = 2130903169;
			
			// aapt resource value: 0x7f030082
			public const int DetalleInventarioItemCodigo = 2130903170;
			
			// aapt resource value: 0x7f030083
			public const int DetalleInventarioItemDescripcion = 2130903171;
			
			// aapt resource value: 0x7f030084
			public const int DetalleInventarioItemFamilia = 2130903172;
			
			// aapt resource value: 0x7f030085
			public const int DetallePedido = 2130903173;
			
			// aapt resource value: 0x7f030086
			public const int DetallePedidoHeaderBarras = 2130903174;
			
			// aapt resource value: 0x7f030087
			public const int DetallePedidoHeaderClase = 2130903175;
			
			// aapt resource value: 0x7f030088
			public const int DetallePedidoHeaderCodigo = 2130903176;
			
			// aapt resource value: 0x7f030089
			public const int DetallePedidoHeaderDescripcion = 2130903177;
			
			// aapt resource value: 0x7f03008a
			public const int DetallePedidoHeaderFamilia = 2130903178;
			
			// aapt resource value: 0x7f03008b
			public const int DetallePedidoItemBarras = 2130903179;
			
			// aapt resource value: 0x7f03008c
			public const int DetallePedidoItemClase = 2130903180;
			
			// aapt resource value: 0x7f03008d
			public const int DetallePedidoItemCodigo = 2130903181;
			
			// aapt resource value: 0x7f03008e
			public const int DetallePedidoItemDescripcion = 2130903182;
			
			// aapt resource value: 0x7f03008f
			public const int DetallePedidoItemFamilia = 2130903183;
			
			// aapt resource value: 0x7f030090
			public const int DetalleVentaConsignacion = 2130903184;
			
			// aapt resource value: 0x7f030091
			public const int DetalleVentaConsignacionHeaderBarras = 2130903185;
			
			// aapt resource value: 0x7f030092
			public const int DetalleVentaConsignacionHeaderClase = 2130903186;
			
			// aapt resource value: 0x7f030093
			public const int DetalleVentaConsignacionHeaderCodigo = 2130903187;
			
			// aapt resource value: 0x7f030094
			public const int DetalleVentaConsignacionHeaderDescripcion = 2130903188;
			
			// aapt resource value: 0x7f030095
			public const int DetalleVentaConsignacionItemBarras = 2130903189;
			
			// aapt resource value: 0x7f030096
			public const int DetalleVentaConsignacionItemClase = 2130903190;
			
			// aapt resource value: 0x7f030097
			public const int DetalleVentaConsignacionItemCodigo = 2130903191;
			
			// aapt resource value: 0x7f030098
			public const int DetalleVentaConsignacionItemDescripcion = 2130903192;
			
			// aapt resource value: 0x7f030099
			public const int ExactusXML = 2130903193;
			
			// aapt resource value: 0x7f03009a
			public const int ExactusXMLX = 2130903194;
			
			// aapt resource value: 0x7f03009b
			public const int FactDiferenciasTF = 2130903195;
			
			// aapt resource value: 0x7f03009c
			public const int FactDiferenciasTFHeader = 2130903196;
			
			// aapt resource value: 0x7f03009d
			public const int FactDiferenciasTFItems = 2130903197;
			
			// aapt resource value: 0x7f03009e
			public const int HistoricosPedido = 2130903198;
			
			// aapt resource value: 0x7f03009f
			public const int HistoricosPedidosHeader = 2130903199;
			
			// aapt resource value: 0x7f0300a0
			public const int HistoricosPedidosHeaderTodos = 2130903200;
			
			// aapt resource value: 0x7f0300a1
			public const int HistoricosPedidosItem = 2130903201;
			
			// aapt resource value: 0x7f0300a2
			public const int HistoricosPedidosItemTodos = 2130903202;
			
			// aapt resource value: 0x7f0300a3
			public const int Impresion = 2130903203;
			
			// aapt resource value: 0x7f0300a4
			public const int JornadaLaboral = 2130903204;
			
			// aapt resource value: 0x7f0300a5
			public const int LineasFacturaLote = 2130903205;
			
			// aapt resource value: 0x7f0300a6
			public const int LineasFacturaLoteHeader = 2130903206;
			
			// aapt resource value: 0x7f0300a7
			public const int LineasFacturaLoteItem = 2130903207;
			
			// aapt resource value: 0x7f0300a8
			public const int LoginHDPI = 2130903208;
			
			// aapt resource value: 0x7f0300a9
			public const int LoginHDPIX = 2130903209;
			
			// aapt resource value: 0x7f0300aa
			public const int LoginT7 = 2130903210;
			
			// aapt resource value: 0x7f0300ab
			public const int LoginT7X = 2130903211;
			
			// aapt resource value: 0x7f0300ac
			public const int LoginXHDPI = 2130903212;
			
			// aapt resource value: 0x7f0300ad
			public const int LoginXHDPIX = 2130903213;
			
			// aapt resource value: 0x7f0300ae
			public const int MainMenu = 2130903214;
			
			// aapt resource value: 0x7f0300af
			public const int MainMenuX = 2130903215;
			
			// aapt resource value: 0x7f0300b0
			public const int MenuActualizador = 2130903216;
			
			// aapt resource value: 0x7f0300b1
			public const int MenuCliente = 2130903217;
			
			// aapt resource value: 0x7f0300b2
			public const int MenuDatos = 2130903218;
			
			// aapt resource value: 0x7f0300b3
			public const int MenuParametros = 2130903219;
			
			// aapt resource value: 0x7f0300b4
			public const int MenuParametrosX = 2130903220;
			
			// aapt resource value: 0x7f0300b5
			public const int MenuReportes = 2130903221;
			
			// aapt resource value: 0x7f0300b6
			public const int MontosConsignacionCia = 2130903222;
			
			// aapt resource value: 0x7f0300b7
			public const int MontosPedido = 2130903223;
			
			// aapt resource value: 0x7f0300b8
			public const int NotaDetalleDesglose = 2130903224;
			
			// aapt resource value: 0x7f0300b9
			public const int NotaVentaConsignacion = 2130903225;
			
			// aapt resource value: 0x7f0300ba
			public const int OpcionComboEnum = 2130903226;
			
			// aapt resource value: 0x7f0300bb
			public const int OpcionDropDownEnum = 2130903227;
			
			// aapt resource value: 0x7f0300bc
			public const int OpcionesCliente = 2130903228;
			
			// aapt resource value: 0x7f0300bd
			public const int OpcionMenuItem = 2130903229;
			
			// aapt resource value: 0x7f0300be
			public const int OpcionMenuItemX = 2130903230;
			
			// aapt resource value: 0x7f0300bf
			public const int ParametrosImpresion = 2130903231;
			
			// aapt resource value: 0x7f0300c0
			public const int ParametrosSistema = 2130903232;
			
			// aapt resource value: 0x7f0300c1
			public const int PruebaImpresion = 2130903233;
			
			// aapt resource value: 0x7f0300c2
			public const int ReporteCierre = 2130903234;
			
			// aapt resource value: 0x7f0300c3
			public const int ReporteCierreCaja = 2130903235;
			
			// aapt resource value: 0x7f0300c4
			public const int ReporteCierreHeader = 2130903236;
			
			// aapt resource value: 0x7f0300c5
			public const int ReporteCierreItem = 2130903237;
			
			// aapt resource value: 0x7f0300c6
			public const int ReporteDevuelto = 2130903238;
			
			// aapt resource value: 0x7f0300c7
			public const int ReporteDevueltoHeader = 2130903239;
			
			// aapt resource value: 0x7f0300c8
			public const int ReporteDevueltoItem = 2130903240;
			
			// aapt resource value: 0x7f0300c9
			public const int ReporteDocDiarios = 2130903241;
			
			// aapt resource value: 0x7f0300ca
			public const int ReporteInventario = 2130903242;
			
			// aapt resource value: 0x7f0300cb
			public const int ReporteInventarioHeaderBarras = 2130903243;
			
			// aapt resource value: 0x7f0300cc
			public const int ReporteInventarioHeaderClase = 2130903244;
			
			// aapt resource value: 0x7f0300cd
			public const int ReporteInventarioHeaderCodigo = 2130903245;
			
			// aapt resource value: 0x7f0300ce
			public const int ReporteInventarioHeaderDescripcion = 2130903246;
			
			// aapt resource value: 0x7f0300cf
			public const int ReporteInventarioHeaderFamilia = 2130903247;
			
			// aapt resource value: 0x7f0300d0
			public const int ReporteInventarioItemBarras = 2130903248;
			
			// aapt resource value: 0x7f0300d1
			public const int ReporteInventarioItemClase = 2130903249;
			
			// aapt resource value: 0x7f0300d2
			public const int ReporteInventarioItemCodigo = 2130903250;
			
			// aapt resource value: 0x7f0300d3
			public const int ReporteInventarioItemDescripcion = 2130903251;
			
			// aapt resource value: 0x7f0300d4
			public const int ReporteInventarioItemFamilia = 2130903252;
			
			// aapt resource value: 0x7f0300d5
			public const int ReporteLiquidacionInventario = 2130903253;
			
			// aapt resource value: 0x7f0300d6
			public const int ReporteVisitaMontos = 2130903254;
			
			// aapt resource value: 0x7f0300d7
			public const int ReporteVisitaMontosHeader = 2130903255;
			
			// aapt resource value: 0x7f0300d8
			public const int ReporteVisitaMontosItem = 2130903256;
			
			// aapt resource value: 0x7f0300d9
			public const int ReporteVisitas = 2130903257;
			
			// aapt resource value: 0x7f0300da
			public const int ReporteVisitasHeader = 2130903258;
			
			// aapt resource value: 0x7f0300db
			public const int ReporteVisitasItem = 2130903259;
			
			// aapt resource value: 0x7f0300dc
			public const int RubrosJornada = 2130903260;
			
			// aapt resource value: 0x7f0300dd
			public const int RubrosJornadaX = 2130903261;
			
			// aapt resource value: 0x7f0300de
			public const int SeleccionClienteHeader = 2130903262;
			
			// aapt resource value: 0x7f0300df
			public const int SeleccionClienteItem = 2130903263;
			
			// aapt resource value: 0x7f0300e0
			public const int SeleccionClientes = 2130903264;
			
			// aapt resource value: 0x7f0300e1
			public const int SeleccionFacturas = 2130903265;
			
			// aapt resource value: 0x7f0300e2
			public const int SeleccionFacturasHeader = 2130903266;
			
			// aapt resource value: 0x7f0300e3
			public const int SeleccionFacturasItem = 2130903267;
			
			// aapt resource value: 0x7f0300e4
			public const int SeleccionNotasCredito = 2130903268;
			
			// aapt resource value: 0x7f0300e5
			public const int SeleccionNotasCreditoHeader = 2130903269;
			
			// aapt resource value: 0x7f0300e6
			public const int SeleccionNotasCreditoItem = 2130903270;
			
			// aapt resource value: 0x7f0300e7
			public const int SeleccionRecibos = 2130903271;
			
			// aapt resource value: 0x7f0300e8
			public const int SeleccionRecibosHeader = 2130903272;
			
			// aapt resource value: 0x7f0300e9
			public const int SeleccionRecibosItem = 2130903273;
			
			// aapt resource value: 0x7f0300ea
			public const int SplashScreen = 2130903274;
			
			// aapt resource value: 0x7f0300eb
			public const int SugeridoVenta = 2130903275;
			
			// aapt resource value: 0x7f0300ec
			public const int SugeridoVentaItem = 2130903276;
			
			// aapt resource value: 0x7f0300ed
			public const int SugerirBoleta = 2130903277;
			
			// aapt resource value: 0x7f0300ee
			public const int TipoDevolucion = 2130903278;
			
			// aapt resource value: 0x7f0300ef
			public const int TipoDevolucionHeader = 2130903279;
			
			// aapt resource value: 0x7f0300f0
			public const int TipoDevolucionItem = 2130903280;
			
			// aapt resource value: 0x7f0300f1
			public const int TomaDevoluciones = 2130903281;
			
			// aapt resource value: 0x7f0300f2
			public const int TomaDevolucionesDocumentos = 2130903282;
			
			// aapt resource value: 0x7f0300f3
			public const int TomaDevolucionesDocumentosItem = 2130903283;
			
			// aapt resource value: 0x7f0300f4
			public const int TomaDevolucionesHeader = 2130903284;
			
			// aapt resource value: 0x7f0300f5
			public const int TomaDevolucionesItem = 2130903285;
			
			// aapt resource value: 0x7f0300f6
			public const int TomaEfectivo = 2130903286;
			
			// aapt resource value: 0x7f0300f7
			public const int TomaFisicaInventario = 2130903287;
			
			// aapt resource value: 0x7f0300f8
			public const int TomaGarantia = 2130903288;
			
			// aapt resource value: 0x7f0300f9
			public const int TomaGarantiaHeader = 2130903289;
			
			// aapt resource value: 0x7f0300fa
			public const int TomaGarantiaItem = 2130903290;
			
			// aapt resource value: 0x7f0300fb
			public const int TomaInventario = 2130903291;
			
			// aapt resource value: 0x7f0300fc
			public const int TomaInventarioHeader = 2130903292;
			
			// aapt resource value: 0x7f0300fd
			public const int TomaInventarioItem = 2130903293;
			
			// aapt resource value: 0x7f0300fe
			public const int TomaPedido = 2130903294;
			
			// aapt resource value: 0x7f0300ff
			public const int TomaPedidoHeader = 2130903295;
			
			// aapt resource value: 0x7f030100
			public const int TomaPedidoItem = 2130903296;
			
			// aapt resource value: 0x7f030101
			public const int TomaTrasiego = 2130903297;
			
			// aapt resource value: 0x7f030102
			public const int TomaVentaConsig = 2130903298;
			
			// aapt resource value: 0x7f030103
			public const int TomaVentaConsigHeader = 2130903299;
			
			// aapt resource value: 0x7f030104
			public const int TomaVentaConsigItem = 2130903300;
			
			// aapt resource value: 0x7f030105
			public const int UbicacionCliente = 2130903301;
			
			// aapt resource value: 0x7f030106
			public const int Visita = 2130903302;
			
			// aapt resource value: 0x7f030107
			public const int ZxingOverlay = 2130903303;
			
			// aapt resource value: 0x7f030108
			public const int zxingscanneractivitylayout = 2130903304;
			
			// aapt resource value: 0x7f030109
			public const int zxingscannerfragmentlayout = 2130903305;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int Abar = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int ApplicationName = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int Loading = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f06000a
			public const int CheckBoxText = 2131099658;
			
			// aapt resource value: 0x7f060014
			public const int DecimalEditText = 2131099668;
			
			// aapt resource value: 0x7f06000c
			public const int Fondo = 2131099660;
			
			// aapt resource value: 0x7f060008
			public const int ListComboText = 2131099656;
			
			// aapt resource value: 0x7f060005
			public const int ListHeaderText = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int ListItemText = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int ListMenuText = 2131099655;
			
			// aapt resource value: 0x7f060015
			public const int MainTheme = 2131099669;
			
			// aapt resource value: 0x7f060009
			public const int RadioButtonText = 2131099657;
			
			// aapt resource value: 0x7f060004
			public const int btnStyleBlackpearl = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int btnStyleBreakerBay = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int btnStyleDefault = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int btnStyleImage = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int btnStyleSeagull = 2131099650;
			
			// aapt resource value: 0x7f06000b
			public const int layout = 2131099659;
			
			// aapt resource value: 0x7f060011
			public const int mediumBoldText = 2131099665;
			
			// aapt resource value: 0x7f060010
			public const int normalBoldText = 2131099664;
			
			// aapt resource value: 0x7f060012
			public const int normalEditText = 2131099666;
			
			// aapt resource value: 0x7f06000e
			public const int normalIdentText = 2131099662;
			
			// aapt resource value: 0x7f06000d
			public const int normalText = 2131099661;
			
			// aapt resource value: 0x7f060013
			public const int numeralEditText = 2131099667;
			
			// aapt resource value: 0x7f06000f
			public const int smallBoldText = 2131099663;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBindableListView = new int[] {
					2130771969,
					2130771970};
			
			// aapt resource value: 1
			public const int MvxBindableListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxBindableListView_MvxItemTemplate = 0;
			
			public static int[] MvxBinding = new int[] {
					2130771968};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			public static int[] MvxHttpImageView = new int[] {
					2130771971};
			
			// aapt resource value: 0
			public const int MvxHttpImageView_MvxHttpSource = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
